//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 09:02:27 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://dietermai.sailaflash.daaaev/1.0.0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dev.dietermai.sailaflash.persistence.xml.node;
